class MyClass MockNotes 
public static void main(String[] args) {
IBIO.Output("Arya Sharma"); //output my name.
}
}
/*
*
*This is used to wrte a comment that requires multiple lines.
*
*/
/** This is used to write a documentation comment */
string : words/letters
int : whole numbers.
double : floating numbers (decimals)
Getting user input : 
import java.util.Scanner;
class......
Read a byte - nextByte()
Read a short - nextShort()
Read an int - nextInt()
Read a long - nextLong()
Read a float - nextFloat()
Read a double - nextDouble()
Read a boolean - nextBoolean()
Read a complete line - nextLine()
Read a word - next()
